### ISSUE TITLE
Improve Manage Reviews implementation and behavior

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#553]
Please do work for this task in a branch called issue-553.

## Current UI problems

RadGrad should implement the following workflow for reviews of courses and opportunities:

1. When a course has been completed, or an opportunity has been verified, it becomes eligible to be reviewed by a student.

2. The student writes a review by going to their Reviews page and filling out a form. For example:

<img width="1417" alt="Screen Shot 2021-05-28 at 8 41 11 AM" src="https://user-images.githubusercontent.com/290288/120011763-7f31cd00-bf93-11eb-90b3-edba35e55bcf.png">

3. When the review has been submitted, it is queued for moderation. This means that it appears in the Admin's Manage Reviews page. For example:

<img width="1208" alt="Screen Shot 2021-05-28 at 9 05 40 AM" src="https://user-images.githubusercontent.com/290288/120012103-ec456280-bf93-11eb-975b-75711f822fe7.png">

4. If the moderator accepts the review, it is made public and appears in the Explorer page. For example:

<img width="1374" alt="Screen Shot 2021-05-28 at 9 08 05 AM" src="https://user-images.githubusercontent.com/290288/120012393-4ba37280-bf94-11eb-83bb-c8f40c382f2e.png">

5. If the moderator rejects the review, they can write a comment explaining what needs to be fixed:

<img width="1374" alt="Screen Shot 2021-05-28 at 9 10 42 AM" src="https://user-images.githubusercontent.com/290288/120012649-a046ed80-bf94-11eb-8a2a-bd9b96423de2.png">

6. In the event of rejection, the student is currently informed through this UI on their reviews page:

<img width="1325" alt="Screen Shot 2021-05-28 at 9 12 36 AM" src="https://user-images.githubusercontent.com/290288/120012905-f9af1c80-bf94-11eb-8890-7fbf0de598ef.png">

Note that the message does not include the moderator comment, which is an error in the UI.

After rejection, the Explorer now shows two entries for the student for the course, which is clearly an error:

<img width="1376" alt="Screen Shot 2021-05-28 at 9 15 10 AM" src="https://user-images.githubusercontent.com/290288/120013220-56aad280-bf95-11eb-9934-7881ccf6d2f4.png">

## How to examine this behavior locally

Bring up a development version locally, then create two separate incognito windows. Login to localhost:3200 in one window as radgrad@hawaii.edu, and navigate to the Manage Reviews page.  Login to localhost:3200 in the other window as abi@hawaii.edu, and navigate to the Reviews page. 

From there, you can step through the review process and how actions by either a student or admin interact with each other and what appears in the Explorer. 

Note that Advisors can also manage reviews, but we will focus on Admin processing for now. 

## Summary of current vs desired behavior

The desired behavior is:

* Students can submit reviews only for completed courses and verified opportunities.
* A submitted review should only appear in the Explorer after being approved by an Admin (this is a change from RadGrad1 behavior, incidentally).
* When a student has submitted a review but it is not yet approved, that review should have some sort of tag associated with it to indicate that it is queued for moderation and not yet publicly available.
* When an admin rejects a review, the student should know it has been rejected, be shown the comments by the admin, and asked to resubmit. (This could even be part of the checklist item).
* When a student revises a rejected review, it should reappear in the admin's queue.
* When the admin approves the review, it should appear in the Explorer. 

The current behavior differs from this in at least the following ways:

* Submitted reviews appear immediately in the Explorer
* Rejected reviews appear in Explorer.
* The Explorer can show both a review and a request for a new review for the same course. 
* Admin comments upon rejection are not communicated to the student.

Additional issues based on student review:

* Reviews page should have course num as well as name in dropdown.
* Clicking "add" on a review does not reset the form, and the page does not indicate the review was added.
* Review submission workflow improvement: indicate when a review has been submitted.
* Review bug: says you should add a review even if you've already made one.

## Current code problems

In addition to the behavioral problems identified above, we performed a code review (#532), which identified the following problems in need of correction in the code:

- [x] Use export default withTracker(...).
- [x] Define typed constants in withTracker().
- [x] Inline the AdminModerationWidget code into ManageReviewsPage.
- [x] Remove Widget and Card suffixes in file names.
- [x] Delete handleAcceptReview and handRejectReview functions.
- [x] Delete isReview parameter.
- [x] Use RadGradSegment in ModerationColumnWidget
- [x] Delete ModerationQuestionCard component
- [ ] Use AutoForm in ModerationReviewCardWidget.
- [x] Delete inappropriate comments

Refer to the review comments for more details.

## Task

Revise the code and behavior to be in accordance with above specifications.
